learning_users/basic_app/urls.py
from basic_app import views
from django.conf.urls import url, include

app_name = 'basic_app'

urlpatterns = [
    url('register/', views.register, name="register"),
]

learning_users/learning_users/urls.py
from basic_app import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', views.index, name="index"),
    path(r'admin/', admin.site.urls),
    path(r'basic_app/', include('basic_app.urls')),
]

learning_users/basic_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from basic_app.models import UserProfileInfo
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from basic_app.forms import UserForm, UserProfileInfoForm
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # extra attributes
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title></title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Django Index Page</h1>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>

    </body>
</html>

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h1>Fill out the form:</h1>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}